# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  checkout-main:
    cmds:
      - git checkout main
      - git pull
  merge-all:
    cmds:
      - task: checkout-main
      - git merge origin/zlog
      - git merge origin/task
      - git merge origin/helper
      - task: push

  push:
    cmds:
      - git push
